### PR TITLE
ci(cicd) add github workflows and commands

### PR DESCRIPTION
**Pull request by michaelwarren1106**
first shot at workflows

i ran eslint/prettier for the first time i think? so there's a lot of linting changes

### CODE REVIEW

**Comment by calebdwilliams** [comment]
This looks good to me so far, but looks like the build is still failing.

**Comment by michaelwarren1106** [comment]
ya it’s breaking because of the helpers tsc build failing. and i think your pr fixes that? so let’s merge your PR first and i’ll rebase and we’ll see?

**Comment by calebdwilliams** [comment]
Merged the helpers branch fyi

**Comment by michaelwarren1106** [comment]
kk i’ll  rebase and try to build

**Comment by calebdwilliams** [comment]
Rebased against main

**Review by calebdwilliams — APPROVED** [review]
This looks good to me. @michaelwarren1106 would you mind reviewing the changes I pushed here as well?

**Review by calebdwilliams — APPROVED** [review]
LGTM

**Pull request merged**
